<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE beans[
        <!ELEMENT beans (bean*)>
        <!ELEMENT bean (property*)>
        <!ELEMENT property (#PCDATA)>

        <!ATTLIST bean id ID #REQUIRED>
        <!ATTLIST bean class CDATA #IMPLIED>
        <!ATTLIST property id CDATA #IMPLIED>
        <!ATTLIST property ref IDREF #IMPLIED>
        ]>
<beans>

    <!--  DAO  -->
    <bean id="userBasicDAO" class="person.cls.qqzone.dao.impl.UserBasicDAOImpl"/>
    <bean id="topicDAO" class="person.cls.qqzone.dao.impl.TopicDAOImpl"/>
    <bean id="replyDAO" class="person.cls.qqzone.dao.impl.ReplyDAOImpl"/>
    <bean id="hostReplyDAO" class="person.cls.qqzone.dao.impl.HostReplyDAOImpl"/>

    <!--  Service  -->
    <bean id="userBasicService" class="person.cls.qqzone.service.impl.UserBasicServiceImpl">
        <property id="userBasicDAO" ref="userBasicDAO"/>
    </bean>
    <bean id="topicService" class="person.cls.qqzone.service.impl.TopicServiceImpl">
        <property id="topicDAO" ref="topicDAO"/>
        <property id="replyService" ref="replyService"/>
        <property id="userBasicService" ref="userBasicService"/>
    </bean>
    <bean id="replyService" class="person.cls.qqzone.service.impl.ReplyServiceImpl">
        <property id="replyDAO" ref="replyDAO"/>
        <property id="hostReplyService" ref="hostReplyService"/>
        <property id="userBasicService" ref="userBasicService"/>
    </bean>
    <bean id="hostReplyService" class="person.cls.qqzone.service.impl.HostReplyServiceImpl">
        <property id="hostReplyDAO" ref="hostReplyDAO"/>
        <property id="userBasicService" ref="userBasicService"/>
    </bean>

    <!--  controller  -->
    <bean id="user" class="person.cls.qqzone.controller.UserController">
        <property id="userBasicService" ref="userBasicService"/>
        <property id="topicService" ref="topicService"/>
    </bean>
    <bean id="page" class="person.cls.qqzone.myssm.controller.PageController"/>
    <bean id="topic" class="person.cls.qqzone.controller.TopicController">
        <property id="topicService" ref="topicService"/>
    </bean>

</beans>